POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Xoms",
    "email": "shabliioleg@gmail.com",
    "password": "password"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "shabliioleg@gmail.com",
    "password": "password"
}

### 

POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MDU1ZDdhNDQyZTM3ZTIyYmNhYjIzNDYiLCJpYXQiOjE2MTYyODgyMTd9.CvfJR0QYRARF2N5TtlX8Gr1Ac0B3hA4WVRzZGxKOmLo" 
}

### 
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MDU1ZDdhNDQyZTM3ZTIyYmNhYjIzNDYiLCJpYXQiOjE2MTYyODg5MTEsImV4cCI6MTYxNjI5MjUxMX0.k-gjy1eUaWcXnLrnIlAT7UKPeIKmGTKgL_Tk8lEWCN8
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MDU1ZDdhNDQyZTM3ZTIyYmNhYjIzNDYiLCJpYXQiOjE2MTYyODg5MTF9.sQfVofxhalSGMk0qUnGo0gRZAvVANL9wT0IgIrlmFFw" 
}

